dist: trusty

cache:
  - pip
  - apt

language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      sudo: required
      dist: xenial

addons:
  apt:
    packages:
      - libspatialindex-dev

install:
  - pip install -e .

script:
  - python -m pytest --doctest-modules rtree tests/test_*
