dist: trusty
sudo: true

language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

before_install:
  - sudo apt-get update
  - sudo apt-get install libspatialindex-dev

install:
  - pip install -e .

script:
  - py.test
