[build-system]
requires = ["wheel", "setuptools>=39.2"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py37', 'py38', 'py39']
color = true
skip_magic_trailing_comma = true

[tool.isort]
profile = "black"
known_first_party = ["rtree"]
skip_gitignore = true
color_output = true
