name: Build and publish

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/deploy.yml'
  push:
    tags:
      - '*'  # Triggers the workflow on version tags
  
permissions:
  contents: write
  actions: read

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include: 
          - os: "windows-latest"
            msvc_arch: "x64"
          - os: "windows-11-arm"
            msvc_arch: "ARM64"
          - os: "ubuntu-latest"
          - os: "ubuntu-24.04-arm"
          - os: "macos-latest"

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      name: Install Python
      with:
        python-version: '3.11'
        
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: ${{ matrix.msvc_arch }}
      if: ${{ matrix.msvc_arch }}
      
    - name: Build wheels
      uses: pypa/cibuildwheel@v3.0.0
      env:         
         CIBW_BUILD: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && '*cp311*' || '*cp310*' }}
         CIBW_BUILD_VERBOSITY: 3
         CIBW_BEFORE_ALL: pip install wheel
         CIBW_REPAIR_WHEEL_COMMAND: python scripts/repair_wheel.py -w {dest_dir} {wheel}
         CIBW_TEST_SKIP: "*-macosx_arm64"
         CIBW_TEST_REQUIRES: tox
         CIBW_TEST_COMMAND: |
           tox --conf {project} --installpkg {wheel}
           
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true
    - uses: pypa/gh-action-pypi-publish@release/v1
   
  # Create GitHub release on version tag    
  github_release:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:   
    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        path: dist
        merge-multiple: true
    - uses: softprops/action-gh-release@v2.3.2      
      with:
        files: dist/*
        body: |
            Unofficial release for testing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
