name: Ubuntu

on:
  pull_request:
    branches:
    - '*'

jobs:
  ubuntu:
    name: ${{ matrix.os }}

    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04']

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      shell: bash -l {0}
      run: |
          sudo apt install libspatialindex-c4v5 python3-pip

    - name: Install
      shell: bash -l {0}
      run: |
        pip3 install setuptools numpy pip --upgrade
        pip3 install -e .
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        pip3 install flake8
        flake8 rtree/
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pip install pytest
        python -m pytest --doctest-modules rtree tests
