name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: pp* *-win32
      CIBW_TEST_REQUIRES: pytest numpy
      CIBW_TEST_COMMAND: "pytest -v {project}/tests"
      # we are copying the shared libraries ourselves so skip magical copy
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
      CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: ""
      CIBW_BEFORE_BUILD_LINUX: "pip install cmake; bash {project}/ci/install_libspatialindex.bash"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.6.4
    - name: Run MacOS Preinstall Build
      if: startsWith(matrix.os, 'macos')
      run: |
        # provides sha256sum
        brew install coreutils
        pip install cmake
        bash ci/install_libspatialindex.bash
    - name: Run Windows Preinstall Build
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install vcpython27 -f -y
        ci\install_libspatialindex.bat
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
    - name: Upload To PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      # TODO : remove `if false` statement after secrets are set in Github UI
      if: false
      run: |
        pip install twine
        twine upload ./wheelhouse/*
