name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: pp* cp27*
      CIBW_TEST_REQUIRES: pytest numpy
      CIBW_TEST_COMMAND: pytest {project}/tests
      CIBW_BEFORE_BUILD_LINUX: "pip install cmake; bash {project}/ci/install_libspatialindex.bash"
      CIBW_BEFORE_BUILD_MACOS: "pip install cmake; bash {project}/ci/install_libspatialindex.bash"
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'
    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.6.4
    - name: Install Homebrew Packages
      if: startsWith(matrix.os, 'macos')
      run: |
        # provides sha256sum
        brew install coreutils
    - name: Run Windows Preinstall Build
      if: startsWith(matrix.os, 'windows')
      #vcpython27
      env:
        CC: C:\msys64\mingw64\bin\clang.exe
        CXX: C:\msys64\mingw64\bin\clang.exe
      run: |
        choco install ninja -f -y 
        ci\install_libspatialindex.bat
        mkdir include
        mkdir lib
        cp ci\build\*.dll lib
        mv ci\build\* include
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
    - name: Upload To PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      # TODO : remove `if false` statement after secrets are set in Github UI
      if: false
      run: |
        pip install twine
        twine upload ./wheelhouse/*
